
server:
  port: 8003
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cplayerapp

  application:
    name: RecommendedService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka